### ISSUE TITLE
Blessings and Affection Max filters in Market

### ISSUE THREAD

**Issue by UncleBob800** [45026831/hh-plus-plus#75]
We still need "Blessings" filter and "Affection Max" filter in Market. 
This filters been very long time in another HH++ mod from Tom208 but still not have in your mod.
![image](https://user-images.githubusercontent.com/86453893/177019649-0dc8b0fd-6196-4b7f-aa45-8ec9d3ab5649.png)
It is very tiring when we need to look girl in the Harem who have a blessing, and then go to the Market to improve this girl. And it is especially tiring when we need to complete the "Upgrade any girl grade" task in Daily Goals and there is no way to hide those girls who have a max grade.

**Comment by syne-** [comment]
I don't really see the point of a blessed filter, just being blessed is not enough of an indicator if the girl is useful this week especially since you don't see their potential if they were maxed out compared to the others. Even in the team building screen it is pretty superfluous since the girl list is sorted by strength including the blessing.

When I build a team for the next week I check the data sheet that is linked on the blessing page and fill a team slot with the seven best ones I have. Then I can filter the market for that team to focus on leveling them up.

Also if you just want to find a few girls to upgrade, choosing affection level 0 stars is most likely good enough.

Just my point of view and workarounds you can use until they are added.

**Comment by 45026831** [comment]
Please don't open duplicate issues, you can add information to #56 still.
